### ISSUE TITLE
Previous Versions of Maps & Modifications Are Not Hidden By Default

### ISSUE THREAD

**Issue by CouncillorMorax** [FAForever/faf-moderator-client#109]
This issue was raised while a M&M vault moderator noticed that a map he uploaded 15 times over the course of a year was not automatically hiding previous revisions. The same effect happens with modifications.

The effect is not noticeable when using the java client, but the python client shows all previous versions in succession while browsing the vault:

![image](https://user-images.githubusercontent.com/23299209/74294318-78823680-4d0b-11ea-815e-e592327d3869.png)

**Comment by Brutus5000** [comment]
The ability to be able to hide single versions instead of the whole map is intentional behavior.
The old map vault showing it wrong is not an issue to me as it is unmaintained and will be shutdown due to php-related security issues anyway.
I asked Strogo previously to rework the map and mod vault in the python client. Guess I should give him a deadline when it will be shutdown.
